[project]
name = "reset-network"
authors = ["Reset Network Team"]
description = "A decentralized network management platform with granular resource allocation and access control"
telemetry = false
requirements = []
[contracts.network-core]
path = "contracts/network-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
